# Generated by Django 5.1.4 on 2024-12-16 11:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_usermodel_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 16, 16, 50, 796000))),
                ('is_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usermodel')),
            ],
        ),
    ]
