# Generated by Django 5.1.4 on 2024-12-16 11:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        ('user', '0004_alter_usermodel_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 16, 19, 26, 700707)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel'),
        ),
    ]
