# Generated by Django 5.1.4 on 2024-12-16 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todomodel_deadline_alter_todomodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 16, 21, 16, 890536)),
        ),
    ]
