# Generated by Django 5.1.4 on 2024-12-16 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('surname', models.CharField(default='', max_length=25)),
                ('yosh', models.IntegerField(default=0)),
                ('birth', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 15, 57, 15, 686143))),
                ('is_student', models.BooleanField(default=False)),
            ],
        ),
    ]
