# Generated by Django 5.1.4 on 2024-12-16 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 16, 5, 53, 301051)),
        ),
    ]
